### ISSUE TITLE
support SPM?

### ISSUE THREAD

**Issue by OHeroJ** [mryu87/EllipticCurve#3]
great!  when support SPM？

**Comment by mryu87** [comment]
oh yes, it's on the way. please note ecdsa signing for secp256k1 is very slow at the moment. it is bottlenecked at UInt256.karatsuba

**Comment by mryu87** [comment]
done: https://github.com/mryu87/EllipticCurve/commit/5fe980239996e40785fa8febd239e25b2ec1464a

**Comment by mryu87** [comment]
let me know if it works for you. :)
