### ISSUE TITLE
Secp256k1 generate a radom private key?

### ISSUE THREAD

**Issue by OHeroJ** [mryu87/EllipticCurve#5]
hello, Can Secp256k1 generate a radom private key? And it can obtain the corresponding public key.
like this: 

```py
def generate_ECDSA_keys():
    sk = ecdsa.SigningKey.generate(curve=ecdsa.SECP256k1)  #this is your sign (private key)
    private_key = sk.to_string().hex()  #convert your private key to hex
    vk = sk.get_verifying_key()  #this is your verification key (public key)

```

**Comment by mryu87** [comment]
this library is only for curves and finite fields. but if you want to generate a random private key, you can use the arc4random_uniform in UInt256 library

**Comment by mryu87** [comment]
again, this library is **VERY SLOW**, its not for production use. please refer to [libsecp256k1](https://github.com/bitcoin-core/secp256k1) for production purposes.

**Comment by OHeroJ** [comment]
get it , very slow
